### ISSUE TITLE
Table overwrite on team results page in Chrome-like browsers

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#30]
The table seems to be escaping its box in Chrome and Brave, though it looks fine in Safari and Firefox. Not sure if other pages are affected yet or not.

https://challenge.fingerlakesrunners.org/Course/228617/Team

![image](https://user-images.githubusercontent.com/36641103/103462636-99bd8e00-4cf4-11eb-9129-df484fe04e24.png)

Acceptance criteria:
* The results table remains contained within its bounding box.

**Comment by stevedesmond-ca** [comment]
Looks like it's the table's responsive scrolling having the wrong breakpoint set -- it shows up in Firefox too, but (for all browsers) only at certain viewport widths: 992-1199px

Easy fix!

**Comment by adamengst** [comment]
Oh, interesting. I must have hit sweet spots for my Safari and Firefox tests...

**Comment by stevedesmond-ca** [comment]
Fixed as of 98d6d77

**Comment by adamengst** [comment]
FWIW, this cosmetic bug is still happening in some places, such as 

![image](https://user-images.githubusercontent.com/36641103/104386440-2ccfa280-5503-11eb-89fe-af3c00b1e7aa.png)

Looks like there's a difference between the breakpoint for the table and for the surrounding white box.

**Comment by stevedesmond-ca** [comment]
Ack, thought I caught them all -- I'll do another pass tonight

**Comment by stevedesmond-ca** [comment]
Took me a while staring at the screenshot after failing to reproduce this myself on any of my devices, but I finally figured it out!

Bootstrap (the CSS framework) uses system fonts as its default. For macOS that means Helvetica Neue, which is wider than Windows, Chrome, Android, and Linux (the devices I have to test with).

I'll pick a standard OSS sans serif font to use cross-platform for better consistency.

**Comment by adamengst** [comment]
Ah, good sleuthing!
